In [3]:
# pip install numpy
# pip install face-recognition  
# pip install cmake
# pip install dlib==19.18
# pip install opencv

In [1]:
import numpy as np
import face_recognition
import cv2
from datetime import datetime

In [2]:
import os
path="images"
images=[]
classNames=[]
myList=os.listdir(path)
print(myList)
for _ in myList:
    curImg=cv2.imread(f"{path}\{_}")
    # curImg=cv2.imread("f{path}/{_}")
    images.append(curImg)
    classNames.append(os.path.splitext(_)[0])
print(len(images))

['abhishake kumar.jpg', 'axith choudhary.jpg', 'devansh toplani.jpg', 'elon bhai 1.jpg', 'jack ma.jpg']
5


In [3]:
def findEncoding(images):
    encodingList=[]
    for img in images:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode=face_recognition.face_encodings(img)[0]
        encodingList.append(encode)
    return encodingList
encodinfListKnow=findEncoding(images)
print("encoding complete")

encoding complete


In [4]:
def markAttendence(name):
    with open("attendence.csv","r+") as f:
        myDataList=f.readlines()
        nameList=[]
        for line in myDataList:
            entry=line.split(",")
            nameList.append(entry[0])
        if name not in nameList:
            now=datetime.now()
            dtString=now.strftime("%H:%M:%S")
            f.writelines(f"\n{name},{dtString}")
         



In [5]:
cap=cv2.VideoCapture(0)


In [ ]:
while True:
    sucess,img=cap.read()
    imgS=cv2.resize(img,(0,0),None,0.25,0.25)
    imgS=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    key = cv2. waitKey(1)

    facesCurFrame=face_recognition.face_locations(imgS)
    encodingCurFrame=face_recognition.face_encodings(imgS,facesCurFrame)

    for encodeFace,faceLoc in zip(encodingCurFrame,facesCurFrame):
        matches=face_recognition.compare_faces(encodinfListKnow,encodeFace)
        faceDis=face_recognition.face_distance(encodinfListKnow,encodeFace)
        print(faceDis)
        matchIndex=np.argmin(faceDis)

        if matches[matchIndex]:
            name=classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1=faceLoc
            y1,x2,y2,x1=y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,0),2)
            cv2.rectangle(img,(x1,y1-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
            markAttendence(name)
        elif key == ord("q"):
            cap.release()
            cv2.destroyAllWindows()
            break

    cv2.imshow("webcam",img)
    cv2.waitKey(1)


[0.68306913 0.30911327 0.71375945 0.79781946 0.84336517]
AXITH CHOUDHARY
[0.65581199 0.28515698 0.73728457 0.84589603 0.83669371]
AXITH CHOUDHARY
[0.64999745 0.20414192 0.75343206 0.84759058 0.80867627]
AXITH CHOUDHARY
[0.66987404 0.20703625 0.74764223 0.80737224 0.82042165]
AXITH CHOUDHARY
[0.66871459 0.20489695 0.74231251 0.81664305 0.83581342]
AXITH CHOUDHARY
[0.64189756 0.22673177 0.74121021 0.87975709 0.8212268 ]
AXITH CHOUDHARY
[0.62700428 0.22223773 0.734101   0.86548581 0.80387904]
AXITH CHOUDHARY
[0.66514272 0.31079047 0.69469829 0.79697582 0.74455844]
AXITH CHOUDHARY
[0.66042584 0.34030463 0.70415958 0.77689394 0.72983182]
AXITH CHOUDHARY
[0.66138803 0.33018627 0.68603611 0.79849349 0.74096629]
AXITH CHOUDHARY
[0.65450265 0.25511377 0.73187846 0.85713618 0.79775839]
AXITH CHOUDHARY
[0.64156105 0.20832747 0.750175   0.84320657 0.80959018]
AXITH CHOUDHARY
[0.64500084 0.22539199 0.73277608 0.853761   0.80619157]
AXITH CHOUDHARY
[0.66419883 0.21500456 0.75051774 0.86077473 0.8035

: 

: 

In [7]:
cv2.destroyAllWindows()
cap.release()